version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
    - echo "Installing dependencies..."
    - npm install -g @angular/cli
  pre_build:
    commands:
    - echo "Running pre-build tasks..."
    - npm install
  build:
    commands:
    - echo "Building the project..."
    - ng build -c production
  artifacts:
    base-directory: dist/my-angular-app # Adjust this path based on your project structure
    files:
    - '**/*' # Adjust this path based on your build output
