version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
    - echo "Installing dependencies..."
    - npm install -g @angular/cli
  pre_build:
    commands:
    - echo "Running pre-build tasks..."
    - npm install
  build:
    commands:
    - echo "Building the project..."
    - ng build --prod
    finally:
    - echo "Build completed successfully."
artifacts:
  files:
  - 'dist/my-angular-project/**/*' # Adjust this path based on your build output
  - 'appspec.yml' # Corrected the typo here
  - 'deploy-scripts/**/*' # Include your deployment scripts
